server:
  port: 80
spring:
  application:
    #配置应用名
    name: uruleserver
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: ${db.username}
    password: ${db.password}
    initialSize: ${db.initialSize}
    minIdle: ${db.minIdle}
    maxActive: ${db.maxActive}
    maxWait: ${db.maxWait}
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 200
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    
---
#本地环境
spring:
  profiles: local

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level:
    root: info
    com.alibaba.druid: debug
    org.mybatis: debug
    org.apache.ibatis: debug
    com.mysql: debug
    com.tz.uruleserver.dao.mapper: debug
    #显示JdbcTemplate的sql执行日志
    org.springframework.jdbc.core: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
  path: /home/tz/Logs/uruleserver

rm:
  config: classpath:config/config-local.properties
---
#开发环境
spring:
  profiles: dev

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level:
    root: info
    com.alibaba.druid: debug
    org.mybatis: debug
    org.apache.ibatis: debug
    com.mysql: debug
    com.tz.uruleserver.dao.mapper: debug
  path: /home/tz/Logs/uruleserver

rm:
  config: classpath:config/config-dev.properties
---
#测试环境
spring:
  profiles: test

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level:
    root: info
  path: /home/tz/Logs/uruleserver

rm:
  config: classpath:config/config-test.properties
---
#online环境
spring:
  profiles: online

  redis:
    cluster:
      nodes: ${redis.cluster.nodes}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level:
    root: info
    com.alibaba.druid: debug
    org.mybatis: debug
    org.apache.ibatis: debug
    com.mysql: debug
    com.tz.uruleserver.dao.mapper: debug
  path: /home/tz/Logs/uruleserver

rm:
  #config: file:/home/tz/Logs/uruleserver/config-online.properties
  config: classpath:config/config-online.properties
